version: '3.8'
services:
  api:
    environment:
      APPLICATION_PORT: 3000
    image: 715820034474.dkr.ecr.eu-west-1.amazonaws.com/webhooks_receiver:latest
    ports:
      - '3000:3000'
    volumes:
      - ./data:/usr/src/webhooks-receiver/data
