version: '3.8'
services:
  api:
    command: yarn dev
    environment:
      APPLICATION_PORT: 3000
      NODE_ENV: local
      TZ: 'Europe/Warsaw'
    image: library/node:16.13.0
    user: node
    ports:
      - '3000:3000'
    volumes:
      - .:/application
    working_dir: /application/api
