version: '3.8'
services:
  api:
    environment:
      APPLICATION_PORT: 3000
      NODE_ENV: production
    image: 715820034474.dkr.ecr.eu-west-1.amazonaws.com/webhooks_receiver:latest
    ports:
      - '443:3000'
    volumes:
      - ./data:/usr/src/webhooks-receiver/data
      - /etc/letsencrypt/:/usr/src/webhooks-receiver/letsencrypt
