#!/usr/bin/env sh

TAG=${1}

aws-vault exec ofadiman -- aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 715820034474.dkr.ecr.eu-west-1.amazonaws.com/webhooks_receiver

docker tag ofadiman/webhooks-receiver:${TAG} 715820034474.dkr.ecr.eu-west-1.amazonaws.com/webhooks_receiver:${TAG}

docker push 715820034474.dkr.ecr.eu-west-1.amazonaws.com/webhooks_receiver:${TAG}
